
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GRACE
 */
public class correctedAssignment extends javax.swing.JFrame {
      ButtonGroup bg = new ButtonGroup();
      
      
      
    /**
     * Creates new form correctedAssignment
     */
    public correctedAssignment() {
        initComponents();
        bg.add(btnMale);
        bg.add(btnFemale);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NamesInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnMale = new javax.swing.JRadioButton();
        btnFemale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        DoBInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PhoneInput = new javax.swing.JTextField();
        IdInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Id");

        NamesInput.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Names");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Gender");

        btnMale.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnMale.setForeground(new java.awt.Color(0, 51, 102));
        btnMale.setText("Male");

        btnFemale.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnFemale.setForeground(new java.awt.Color(0, 51, 102));
        btnFemale.setText("Female");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("DoB");

        DoBInput.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        DoBInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoBInputActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Phone");

        PhoneInput.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        PhoneInput.setText(" ");

        IdInput.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        IdInput.setText(" ");

        Table.setAutoCreateRowSorter(true);
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Table);

        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(0, 102, 0));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(51, 102, 0));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(51, 102, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRead.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnRead.setForeground(new java.awt.Color(51, 102, 0));
        btnRead.setText("Read");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("      Student Registration System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(btnCreate)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRead)
                                        .addGap(32, 32, 32)
                                        .addComponent(btnUpdate)
                                        .addGap(29, 29, 29)
                                        .addComponent(btnDelete))
                                    .addComponent(NamesInput, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(PhoneInput, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DoBInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnMale)
                                .addGap(18, 18, 18)
                                .addComponent(btnFemale))))
                    .addComponent(jLabel1))
                .addGap(0, 101, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(IdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamesInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMale)
                    .addComponent(jLabel3)
                    .addComponent(btnFemale))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(DoBInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(PhoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnRead)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoBInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoBInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoBInputActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
       String id=IdInput.getText();
       String name=NamesInput.getText();
       String gender="";
       if(btnFemale.isSelected()==true){
       gender="Female";
       }else{
       gender="Male";
       }
       String dob=DoBInput.getText();
       String phone=PhoneInput.getText();
          
        try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new com.mysql.jdbc.Driver()); 
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","");
            PreparedStatement st=con.prepareStatement("insert into StudentInfo Values(?,?,?,?,?)");
            
            st.setString(1, id);
            st.setString(2, name);
            st.setString(3, gender);
            st.setString(4, dob);
            st.setString(5, phone);
            
            int row=st.executeUpdate(); // save and return rows affected
            st.close();
            con.close();
             JOptionPane.showMessageDialog(this, row+" Created");
           
            
            
        } catch (SQLException ex) {
            Logger.getLogger(correctedAssignment.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        // TODO add your handling code here:
        
        try{
         DriverManager.registerDriver(new com.mysql.jdbc.Driver());        
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root",""); 
         
         
         PreparedStatement pst=con.prepareStatement("select * from StudentInfo");
    
         ResultSet rs=pst.executeQuery();
         
         DefaultTableModel model= new DefaultTableModel();
         Object cols[] = new Object[5];
         cols[0]="ID";
         cols[1]="Name";
         cols[2]="Gender";
         cols[3]="DoB";
         cols[4]="Phon";
         model.setColumnIdentifiers(cols);
         
          while(rs.next()){
         Object row[]=new Object[5];
                  row[0]=rs.getInt(1);
                  row[1]=rs.getString(2);
                  row[2]=rs.getString(3);
                  row[3]=rs.getString(4);
                  row[4]=rs.getInt(5);
                  
                  model.addRow(row);
          }
           Table.setModel(model);
        
         
         
          
         
         
        }catch(Exception ex){
            
           ex.getMessage();
        }
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        
         try {
            // TODO add your handling code here:
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","");
         
           
             PreparedStatement pst = con. prepareStatement("update StudentInfo set Name=? where Id=?");
             
            pst.setString(1, NamesInput.getText());
            pst.setString(2, IdInput.getText());
            int r=pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, r+ " updated");
            pst.close();
            con.close();
        } catch (Exception ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
          try {
              // TODO add your handling code here:
              DriverManager.registerDriver(new com.mysql.jdbc.Driver());
              Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql","root","");
               PreparedStatement pst = con. prepareStatement("delete from StudentInfo where id=?");
             
            
            pst.setString(1, IdInput.getText());
            int r=pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, r+ "Deleted");
            pst.close();
            con.close();
              
              
              
              
          } catch (SQLException ex) {
              Logger.getLogger(correctedAssignment.class.getName()).log(Level.SEVERE, null, ex);
          }
         
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(correctedAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(correctedAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(correctedAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(correctedAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new correctedAssignment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DoBInput;
    private javax.swing.JTextField IdInput;
    private javax.swing.JTextField NamesInput;
    private javax.swing.JTextField PhoneInput;
    private javax.swing.JTable Table;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    public javax.swing.JRadioButton btnFemale;
    public javax.swing.JRadioButton btnMale;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
